#!/bin/sh

if [ -e /usr/local/bin/python3 ]; then
   PYTHON_BINS=`/usr/local/bin/python3 -c 'import sysconfig; print(sysconfig.get_paths()["scripts"])'`
   PYTHON_LIBS=`/usr/local/bin/python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])'`
   PYTHON_VERS=`/usr/local/bin/python3 -V | cut -f2 -d " " | cut -f1 -f2 -d "."`
fi

if [ "$?" != "0" ] || [ "$PYTHON_BINS" == "" ] || [ ! -d "$PYTHON_BINS" ] || [ "$PYTHON_LIBS" == "" ] || [ ! -d "$PYTHON_LIBS" ] || [ "$PYTHON_VERS" == "" ]; then

   echo
   echo "                           Python 3 is not installed properly."
   echo
   echo "      Please download and install the current version of Python 3 from 'python.org'."
   sleep 10
   exit

fi

cd "`/usr/bin/dirname "$0"`"
/usr/bin/curl -o searx-master.zip -L https://github.com/searx/searx/archive/master.zip
if [ "$?" == "0" ]; then

   /usr/bin/unzip searx-master.zip
   if [ -d searx-master ]; then
   
      echo "Please enter the administrator password:"
      if [ ! -d /usr/local/etc ]; then
         /usr/bin/sudo /bin/mkdir -p /usr/local/etc
      fi
      /usr/bin/sudo /bin/cp -p searx-settings.yml /usr/local/etc/searx-settings.yml
      if [ "$?" == "0" ]; then

         /usr/bin/sudo /usr/bin/sed -e "s|ultrasecretkey|`/usr/bin/openssl rand -hex 32`|" -i "" /usr/local/etc/searx-settings.yml
         /usr/bin/grep -q ultrasecretkey /usr/local/etc/searx-settings.yml
         if [ "$?" == "1" ]; then

            cd searx-master
            /usr/bin/sed -Ee "s|/{1,2}\**# sourceMappingURL=.*.map.*||" -i "" searx/static/themes/*/*/*.min.*

            /usr/bin/sudo /bin/rm -rf "$PYTHON_LIBS/searx-*.egg"
            /usr/bin/sudo /bin/rm  -f "$PYTHON_LIBS/searx"

            /usr/bin/sudo -H "$PYTHON_BINS/python3" -m pip install --upgrade pip
            if [ "$?" == "0" ]; then

               /usr/bin/sudo -H "$PYTHON_BINS/pip3" install pyyaml
               if [ "$?" == "0" ]; then

                  /usr/bin/sudo -H "$PYTHON_BINS/python3" setup.py install

                  SEARX_VERS=`/usr/bin/sed -n '/^Version: /{s///;p;}' searx.egg-info/PKG-INFO`
                  if [ "$?" == "0" ] && [ "$SEARX_VERS" != "" ]; then

                     /usr/bin/sudo /bin/ln -s searx-$SEARX_VERS-py$PYTHON_VERS.egg/searx "$PYTHON_LIBS/searx"
                     if [ "$?" == "0" ]; then

                        cd ..
                        /usr/bin/sed -e "s|PYTHON3_PATH|$PYTHON_BINS/python3|;s|SEARX_WEBAPP_PATH|$PYTHON_LIBS/searx/webapp.py|" searx.in > searx.plist
                        /usr/bin/sudo /usr/sbin/chown root:wheel searx.plist
                        /usr/bin/sudo /bin/mv searx.plist /Library/LaunchDaemons/

                        echo
                        echo "                SearX has been successfully installed."
                        echo
                        echo "          For a one-time start, you may open the script 'start searx'."
                        echo "      Anyway, SearX will be activated automatically on restart of the Mac."
                     else
                        echo
                        echo "      SearX could not be properly configured."
                     fi
                  else
                     echo
                     echo "      Puthon 3 could not install SearX."
                  fi
               else
                  echo
                  echo "      Pip 3 does not work correctly."
               fi
            else
               echo
               echo "      Puthon 3 does not work correctly."
           fi
         else
            echo
            echo "      Could not configure 'searx-settings.yml'."
         fi
      else
         echo
         echo "      Authorization failed."
      fi
   else
      echo
      echo "      Could not unzip the source code of SearX."
   fi

   cd "`/usr/bin/dirname "$0"`"
   /usr/bin/sudo /bin/rm -r searx-master*

else
   echo
   echo "      Could not download the source code of SearX."
fi

sleep 10
