#!/bin/sh

echo "Please enter the administrator password:"
/usr/bin/sudo /usr/sbin/chown root:wheel /Library/LaunchDaemons/searx.plist
if [ "$?" == "0" ]; then
   SEARX_IS_RUNNING=`/usr/bin/sudo launchctl list | /usr/bin/grep SearX`
   if [ "$SEARX_IS_RUNNING" != "" ]; then
      /usr/bin/sudo launchctl unload /Library/LaunchDaemons/searx.plist
      if [ "$?" == "0" ]; then
         echo
         echo "      SearX has been stopped."
      else
         echo
         echo "      Failed to stop SearX."
      fi
   else
      echo
      echo "      SearX is not running."
   fi
else
   echo
   echo "      Authorization for '/Library/LaunchDaemons/searx.plist' failed."
fi

sleep 10
